set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(ARM_NONE_EABI_GCC arm-none-eabi-gcc REQUIRED)
find_program(ARM_NONE_EABI_AR arm-none-eabi-ar REQUIRED)
find_program(ARM_NONE_EABI_RANLIB arm-none-eabi-ranlib REQUIRED)
find_program(ARM_NONE_EABI_OBJCOPY arm-none-eabi-objcopy REQUIRED)
find_program(ARM_NONE_EABI_SIZE arm-none-eabi-size REQUIRED)

set(CMAKE_C_COMPILER "${ARM_NONE_EABI_GCC}")
set(CMAKE_ASM_COMPILER "${ARM_NONE_EABI_GCC}")
set(CMAKE_AR "${ARM_NONE_EABI_AR}")
set(CMAKE_RANLIB "${ARM_NONE_EABI_RANLIB}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)

set(DAS_MCU_FLAGS "-mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard")
set(CMAKE_C_FLAGS_INIT "${DAS_MCU_FLAGS} -ffreestanding -fno-builtin -ffunction-sections -fdata-sections")
set(CMAKE_ASM_FLAGS_INIT "${DAS_MCU_FLAGS} -x assembler-with-cpp")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${DAS_MCU_FLAGS} -Wl,--gc-sections")

set(CMAKE_C_FLAGS_DEBUG "-O0 -g3" CACHE INTERNAL "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "-O2" CACHE INTERNAL "" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g3" CACHE INTERNAL "" FORCE)

set(DAS_ARM_OBJCOPY "${ARM_NONE_EABI_OBJCOPY}" CACHE FILEPATH "ARM objcopy")
set(DAS_ARM_SIZE "${ARM_NONE_EABI_SIZE}" CACHE FILEPATH "ARM size")
